
DROP TABLE customers;
DROP TABLE films;
DROP TABLE tickets;

CREATE TABLE customers(
  id SERIAL8 PRIMARY KEY NOT NULL,
  name VARCHAR(255),
  funds INT
);

CREATE TABLE films(
  id SERIAL8 PRIMARY KEY NOT NULL,
  title VARCHAR(255),
  price INT
);

CREATE TABLE tickets(
  id SERIAL8 PRIMARY KEY NOT NULL,
  customer_id INT8 REFERENCES customers(id) ON DELETE CASCADE,
  film_id INT8 REFERENCES films(id) ON DELETE CASCADE
);
